### ISSUE TITLE
Moving pywt forward faster

### ISSUE THREAD

**Issue by rgommers** [rgommers/pywt#60]
@aaren @grlee @kwohlfahrt I've been trying to get back to moving ``pywt`` forward, but am having trouble spending enough time on it. I don't want to be a bottleneck here. You guys all have PRs open that look quite good, and you seem interested in the development (I also see some of you commenting on each other's PRs). So I'd like to propose the following:
- I give you commit rights for this repo
- We work on it together with the same rules of the game as we have for Scipy development (I assume you're familiar with those to some extent, but otherwise see [1, 2]).

What do you think?

Ralf

(note: I'll be offline until next Friday, so will see respond to any replies then)

[1] https://github.com/scipy/scipy/blob/master/doc/MAINTAINERS.rst.txt#some-unwritten-rules-of-scipy-development-written-down
[2] https://github.com/scipy/scipy/blob/master/HACKING.rst.txt

**Comment by grlee77** [comment]
@rgommers:

Thanks for the offer!  I am interested in contributing when I can.  I am trying to catch up on some publications/grant writing over the summer and probably won't have time to work on anything substantial for pywt, but I should be able to find some time to help review pull requests, etc.

**Comment by aaren** [comment]
@rgommers - thanks for the invite :)

I'm finishing my thesis right now so don't have very much time available, except for cursory overviews. Should be over by the end of the summer though (I was hoping to be finished sooner and spend some summer working on wavelets...).

I suppose motivations matter here: mine is mostly a desire to get wavelets (continuous as well) into scipy. Working on pywt is a means to that.

I'm happy working within the dev rules. About mailing list discussion: should we use scipy-dev or pywavelets? I'd lean towards scipy-dev as it's more active and that's where I see it heading.

**Comment by kwohlfahrt** [comment]
I'm also happy with the dev rules and would be happy to contribute any work I do on this. I'm happy with the scipy dev rules, they seem fairly reasonable. I don't have much experience working on team projects, so I'm happy to write/clean up code, but would very much appreciate people around to review it.

Regarding motivations, I'm not too fussed about scipy integration, and would prefer for pywt to continue to be available as a standalone package. I think it would be nice if the C part (i.e. 1D convolutions and wavelet transforms) was portable so it could be used as a basis for implementing wavelet transforms in other languages as well.

**Comment by rgommers** [comment]
Great! You all have merge/push rights for this repo now.

Regarding our motivations, they're not perfectly aligned but I can see them meshing together. I started the fork to get good DWT support in Scipy, however it's taking a while to get that done - so in the meantime I'm thinking about cutting a couple of releases of pywt as a standalone package. I got multiple requests for that already, and there clearly is a lot of interest in the package. Refactoring code to expose a clean C or Cython core is always a good idea imho, and allowing code reuse from for example Julia would be interesting.

**Comment by rgommers** [comment]
Regarding releases, a v0.3.0 which is backwards-compatible with the last release from @nigma but with Python 3 support would be a first one. Then a v0.4.0 and on with new features and API changes where needed. What do you think?

**Comment by grlee77** [comment]
That sounds good to me.  I have opened #61 to discuss issues for v0.3.0.  I would appreciate any feedback there on the items I brought up or on any other areas you think will need attention before a release.

**Comment by rgommers** [comment]
Okay, we're good here so closing this issue.
